### ISSUE TITLE
pos neg strided_slice bug? 

### ISSUE THREAD

**Issue by gokunwu** [pl8787/MatchPyramid-TensorFlow#12]
https://github.com/pl8787/MatchPyramid-TensorFlow/blob/36271e46e8301fc429e52ebcb40bae91b41bc24b/model/model_mp.py#L59-L60

should be:
 `     pos = tf.strided_slice(self.pred, [0], [self.batch_size * 2], [2])
  `
`neg = tf.strided_slice(self.pred, [1], [self.batch_size * 2], [2])`
?

**Comment by pl8787** [comment]
@earthwu  It is right here, because `self.batch_size = tf.shape(self.X1)[0]` and the first dimension of X1 equals to 2 times original batch size.

**Comment by gokunwu** [comment]
> @earthwu It is right here, because `self.batch_size = tf.shape(self.X1)[0]` and the first dimension of X1 equals to 2 times original batch size.

yes, i kown you are right
