### ISSUE TITLE
dynamic_pooling_index的来源

### ISSUE THREAD

**Issue by fuhuamosi** [pl8787/MatchPyramid-TensorFlow#2]
你好，看了你的model/model_mp.py中dynamic_pooling_index函数的设计，觉得很巧妙。想问下这个设计是原创的还是参考哪篇论文的？

**Comment by pl8787** [comment]
Hi, @fuhuamosi , the dynamic pooling layer is designed by myself. It is designed to implement MatchPyramid, which you can refer paper [https://arxiv.org/abs/1602.06359]
