### ISSUE TITLE
how to implement dynamic pooling?

### ISSUE THREAD

**Issue by ALiZeyu** [pl8787/MatchPyramid-TensorFlow#4]
Hi, Liang Pang. thank you for sharing your code, it really helps a lot. I have trouble understanding the ' dynamic pooling' part of model_mp.py. especially the 'dynamic_pooling_index(self, len1, len2, max_len1, max_len2)' function. could you please explain how dynamic pooling is implement by this function and gather_nd? thanks!

**Comment by ALiZeyu** [comment]
With the help of @fuhuamosi, I finally understand the meaning of dynamic_pooling_index(). the point is filling padding with words. For example the doc is 'abc' , max_len=6,after dynamic_pooling_index() and gather_nd you 'll get 'aabbcc', this is better than just pooling on padding.

**Comment by pl8787** [comment]
@ALiZeyu  OK, Thanks @fuhuamosi.
