### ISSUE TITLE
tf.gather_nd error

### ISSUE THREAD

**Issue by yudong27** [pl8787/MatchPyramid-TensorFlow#5]
When using tensorflow 1.0.1, error occured as follow:
Must have updates.shape = indices.shape[:IXDIM] + params_shape[IXDIM:], got updates.shape [128,20,500,8], indices.shape [128,20,500,3], params_shape [128,20,500,8]

In tensorflow 1.3.0, the code works well

**Comment by pl8787** [comment]
It might be a bug from tensorflow 1.0.1.
https://github.com/tensorflow/tensorflow/issues/7585#issuecomment-287001974

**Comment by moluxiaobei** [comment]
问题解决了吗，为什么我用1.3还是同样的问题
